language: python

python:
  - '2.7'

install:
  - pip install pytest-cov
  - pip install -r requirements.txt

before_script:
  - cd tests
script:
- pytest tests
- pytest --cov=app

after_success:
 - coveralls